# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: Releases

on:
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  releases:
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v3
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 6.0.x
      - name: Publish
        run: dotnet publish --configuration Release --self-contained --output MArchiveBatchTool-${{ runner.os }}
      - name: Archive (not Windows)
        if: runner.os != 'Windows'
        run: tar -czf MArchiveBatchTool-${{ runner.os }}.tar.gz MArchiveBatchTool-${{ runner.os }}
      - name: Upload build (Windows)
        if: runner.os == 'Windows'
        uses: actions/upload-artifact@v3
        with:
          name: MArchiveBatchTool-${{ runner.os }}
          path: MArchiveBatchTool-${{ runner.os }}
      - name: Upload build (not Windows)
        if: runner.os != 'Windows'
        uses: actions/upload-artifact@v3
        with:
          name: MArchiveBatchTool-${{ runner.os }}
          path: MArchiveBatchTool-${{ runner.os }}.tar.gz
